kind: Service
apiVersion: v1
metadata:
  name: seller-app-service
  annotations:
    cloud.google.com/backend-config: '{"default": "seller-app-service-config"}'
spec:
  type: NodePort
  selector:
    app: seller-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 31017