apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  labels:
    name: gateway-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: user-app-service
            port:
              number: 80
      - pathType: Prefix
        path: /users
        backend:
          service:
            name: user-app-service
            port:
              number: 80
      - pathType: Prefix
        path: /sellers
        backend:
          service:
            name: seller-app-service
            port:
              number: 80
      - pathType: Prefix
        path: /customers
        backend:
          service:
            name: customer-app-service
            port:
              number: 80