version: '3.8'

services:
  user_app:
    build: ./src/users
    container_name: user_app
    ports:
      - "5000:5000"
    env_file: 
      - .env
    environment:
      POSTGRES_DB_URI: ${DB_USERS_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - user_net
      - app_net
  user_db:
    image: postgres:16-alpine
    container_name: user_db
    restart: always
    ports:
      - "5433:5432"     
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${USERS_POSTGRES_DB}
      POSTGRES_USER: ${USERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      TZ: America/Bogota
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users_db" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - user_net
  customer_app:
    build: ./src/customers
    container_name: customer_app
    ports:
      - "5001:5001"
    env_file: 
      - .env
    environment:
      POSTGRES_DB_URI: ${DB_CUSTOMERS_URI}
      USER_SERVICE_URL: ${USER_SERVICE_URL}    
    depends_on:
      customer_db:
        condition: service_healthy
    networks:
      - customer_net
      - app_net
  
  customer_db:
    image: postgres:16-alpine
    container_name: customer_db
    restart: always
    ports:
      - "5434:5432"     
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${CUSTOMERS_POSTGRES_DB}
      POSTGRES_USER: ${CUSTOMERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CUSTOMERS_POSTGRES_PASSWORD}
      TZ: America/Bogota
    volumes:
      - postgres_data_customers:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d customers_db" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - customer_net      
 
networks:
  app_net:
    driver: bridge
    name: app_net
  user_net:
    driver: bridge
    name: user_net
  customer_net:
    driver: bridge
    name: customer_net

volumes:
  postgres_data_users:
  postgres_data_customers: