apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app
  labels:
    app: orders-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        app: orders-app
    spec:
      containers:
      - name: orders-app
        image: us-central1-docker.pkg.dev/proyecto-final-452204/uniandes-misw-proyecto-final/orders:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: "POSTGRES_DB_URI"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: uri
          - name: "JWT_SECRET_KEY"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: JWT_SECRET_KEY
          - name: "ALLOWED_ORIGINS"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: ALLOWED_ORIGINS
          - name: "PATH_API_USER"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: PATH_API_USER
          - name: "PATH_API_BASE"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: PATH_API_BASE
        ports:
          - containerPort: 5000
        imagePullPolicy: Always
      volumes:
        - name: appsecrets-volume
          secret:
            secretName: appsecrets