apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: customer-app-service-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5002
    type: HTTP
    requestPath: /customers/ping