apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: recommendation-app-service-config
spec:
  connectionDraining:
    drainingTimeoutSec: 0
  timeoutSec: 600
  maxRequestBytes: 943718400
  healthCheck:
    checkIntervalSec: 30
    port: 5006
    type: HTTP
    requestPath: /recommendations/ping