apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-app
  labels:
    app: recommendations-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations-app
  template:
    metadata:
      labels:
        app: recommendations-app
    spec:
      serviceAccountName: gcs-ksa
      containers:
      - name: recommendations-app
        image: us-central1-docker.pkg.dev/proyecto-final-452204/uniandes-misw-proyecto-final/recommendations:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: "POSTGRES_DB_URI"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: uri
          - name: "JWT_SECRET_KEY"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: JWT_SECRET_KEY
          - name: "ALLOWED_ORIGINS"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: ALLOWED_ORIGINS
          - name: "NAME_BUCKET_RECOMMENDATIONS"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: NAME_BUCKET_RECOMMENDATIONS
          - name: "OPENAI_API_KEY"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: OPENAI_API_KEY
          - name: "OPENAI_PROMPT"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: OPENAI_PROMPT
          - name: "OPENAI_NRO_FRAMES"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: OPENAI_NRO_FRAMES
          - name: "OPENAI_MODEL"
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: OPENAI_MODEL
        ports:
          - containerPort: 5006
        imagePullPolicy: Always
      volumes:
        - name: appsecrets-volume
          secret:
            secretName: appsecrets