kind: Service
apiVersion: v1
metadata:
  name: recommendation-app-service
  annotations:
    cloud.google.com/backend-config: '{"default": "recommendation-app-service-config"}'
spec:
  type: NodePort
  selector:
    app: recommendations-app
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5006
      nodePort: 31022