apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: product-app-service-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5003
    type: HTTP
    requestPath: /products/ping