kind: Service
apiVersion: v1
metadata:
  name: warehouse-app-service
  annotations:
    cloud.google.com/backend-config: '{"default": "warehouse-app-service-config"}'
spec:
  type: NodePort
  selector:
    app: warehouses-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5009
      nodePort: 31026