name: Integración continua rama develop
on:
    push:
      branches: [ release ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.10'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas unitarias
      id: correr-pruebas
      run: pytest
    - name: Validar resultado con errores
      id: error
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "Una o varias pruebas fallaron"
    - name: Cálculo de cubrimiento
      id: cubrimiento
      if: ${{ success() }}
      run: |
          coverage run -m pytest
          coverage report -m
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: generate-release
    steps:
      - name: Merge Release a Main
        if: ${{ contains(github.event.head_commit.message, 'release') }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main
      